name: Build wiliwili

on:
  push:
    branches: ["dev"]
  pull_request:
  workflow_dispatch:
    inputs:
      ssh_darwin:
        description: 'SSH connection to Darwin'
        required: false
        default: 'false'
      ssh_ubuntu:
        description: 'SSH connection to Ubuntu'
        required: false
        default: 'false'
      universal_macos:
        description: 'build macos (universal)'
        required: false
        default: 'false'
      release:
        description: 'Push a new release'
        required: false
        default: 'false'
      version:
        description: 'Version'
        required: false
        default: '0.0.0'

jobs:
  build-win:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: x86_64, sys: mingw64, env: x86_64, driver: gl }
          - { arch: x86_64, sys: mingw64, env: x86_64, driver: d3d, cmake: "-DUSE_D3D11=ON" }
          - { arch: x86, sys: mingw32, env: i686, driver: gl, cmake: "-DUSE_GL2=ON" }
          - { arch: x86, sys: mingw32, env: i686, driver: d3d, cmake: "-DUSE_D3D11=ON" }
          - { arch: arm64, sys: clangarm64, env: clang-aarch64, driver: d3d, cmake: "-DUSE_D3D11=ON" }
        exclude:
          - { arch: arm64, driver: gl }
        arch: [ x86_64, x86, arm64 ]
        driver: [ gl, d3d ]
    runs-on: ${{ contains(matrix.sys, 'arm64') && 'windows-11-arm' || 'windows-latest' }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        id: msys2
        with:
          msystem: ${{ matrix.sys }}
          path-type: inherit
          cache: false
          release: ${{ contains(matrix.sys, 'arm64') }}
          install: >-
            mingw-w64-${{ matrix.env }}-ninja
            mingw-w64-${{ matrix.env }}-pkgconf
            mingw-w64-${{ matrix.env }}-cc
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 2
          fetch-tags: true
      - name: Install dependency
        run: |
          for pkg in curl-8.21.0-2 mpv-0.41.0-3 libwebp-1.6.0-1; do
            curl -sLO https://github.com/dragonflylee/mpv-build/releases/download/mingw-package/${MINGW_PACKAGE_PREFIX}-${pkg}-any.pkg.tar.zst
          done
          pacman -U --noconfirm *.pkg.tar.zst

          curl -sLO https://github.com/rainers/cv2pdb/releases/download/v0.54/cv2pdb-0.54.zip
          unzip cv2pdb-0.54.zip cv2pdb64.exe -d /usr/bin
      - if: matrix.sys == 'mingw32'
        name: Config Editbin
        shell: powershell
        run: |
          $vcvarsall_path = vswhere.exe -latest -products * -find "VC\Auxiliary\Build\vcvarsall.bat"
          $cc1_path = Get-ChildItem -Path "${{ steps.msys2.outputs.msys2-location }}\mingw32\lib\gcc" -Filter cc1plus.exe -Recurse -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }
          cmd.exe /c "call ""$vcvarsall_path"" x86_amd64 && editbin /LARGEADDRESSAWARE $cc1_path"
      - name: Update gamepad db
        run: |
          BRLS_GLFW=library/borealis/library/lib/extern/glfw
          cmake -P ${BRLS_GLFW}/CMake/GenerateMappings.cmake ${BRLS_GLFW}/src/mappings.h.in ${BRLS_GLFW}/src/mappings.h
      - name: Build
        run: |
          cmake -B build -G Ninja ${{ matrix.cmake }} \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DPLATFORM_DESKTOP=ON \
            -DWIN32_TERMINAL=OFF \
            -DUSE_SYSTEM_CURL=ON \
            -DUSE_LIBROMFS=ON \
            -DBRLS_UNITY_BUILD=OFF \
            -DZLIB_USE_STATIC_LIBS=ON \
            -DVERSION_BUILD=${{ github.run_number }}
          cmake --build build
          cv2pdb64 build/wiliwili.exe
          cp -a README.md ${MINGW_PREFIX}/bin/libmpv-2.dll build
      - name: Upload dist
        uses: actions/upload-artifact@v6
        with:
          name: wiliwili-Windows-${{ matrix.driver }}-${{ matrix.arch }}-${{ github.run_number }}
          path: |
            build/wiliwili.exe
            build/wiliwili.pdb
            build/libmpv-2.dll
            build/README.md

#  build-win-uwp:
#    needs: [ version ]
#    runs-on: windows-2022
#    steps:
#      - name: Install NSIS
#        shell: powershell
#        run: |
#          Invoke-Expression (Invoke-Webrequest 'https://xmake.io/psget.text' -UseBasicParsing).Content
#      - uses: actions/checkout@v6
#        with:
#          submodules: recursive
#          fetch-depth: 0
#      - name: Cache xmake packages
#        uses: actions/cache@v4
#        with:
#          key: ${{ runner.os }}-xmake
#          path: |
#            ${{ runner.temp }}/.xmake/packages
#      - name: build
#        shell: powershell
#        env:
#          VERSION: ${{ needs.version.outputs.VERSION }}
#        run: |
#          $env:path+=";$env:USERPROFILE\xmake"
#          $env:XMAKE_GLOBALDIR="${{ runner.temp }}"
#          xmake f -c -y -v --sw=y --winrt=y --window=sdl --driver=d3d11
#          xmake b -y -v wiliwili
#          cp winrt/key.pfx build/
#          cp winrt/docs/key.pdf build/key.pdf
#      - uses: actions/upload-artifact@v6
#        with:
#          name: ${{ needs.version.outputs.DIST_UWP }}
#          path: |
#            build/wiliwili.msix
#            build/key.pfx
#            build/key.pdf

  build-switch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { driver: opengl }
          - { driver: deko3d, shuffix: "_deko3d" }
        driver: [opengl, deko3d]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 2
          fetch-tags: true

      - name: Build Nro
        run: |
          docker run --rm -v $(pwd):/data devkitpro/devkita64:20260219 bash -c "/data/scripts/build_switch${{ matrix.shuffix }}.sh"

      - name: Upload dist
        uses: actions/upload-artifact@v6
        with:
          name: wiliwili-NintendoSwitch-${{ matrix.driver }}-${{ github.run_number }}
          path: "cmake-build-switch/wiliwili.nro"

  build-ps4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 2
          fetch-tags: true

      - name: Build
        run: |
          docker run --rm -v $(pwd):/src/ xfangfang/wiliwili_ps4_builder:latest \
            "git config --global --add safe.directory /src &&
             cmake -B cmake-build-ps4 -DPLATFORM_PS4=ON \
                -DCMAKE_BUILD_TYPE=Release \
                -DMPV_NO_FB=ON \
                -DBRLS_UNITY_BUILD=OFF \
                -DVERSION_BUILD=${{ github.run_number }}
                make -C cmake-build-ps4 -j$(nproc)"

      - name: Upload dist
        uses: actions/upload-artifact@v6
        with:
          name: wiliwili-PS4-${{ github.run_number }}
          path: cmake-build-ps4/*.pkg

      - name: Upload oelf
        uses: actions/upload-artifact@v6
        with:
          name: ps4_dev_oelf
          path: cmake-build-ps4/*.oelf

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [ IntelChip, AppleSilicon ]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 2
          fetch-tags: true

      - name: install deps
        run: |
          brew install create-dmg dylibbundler
          curl -sSL https://github.com/dragonflylee/mpv-build/releases/download/macos-dylib/dylib-mpv41-${{ matrix.arch }}.tar.gz | tar zxf - -C ${{ runner.temp }}

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh_darwin == 'true' && github.event.inputs.ssh_darwin  != 'false') || contains(github.event.action, 'ssh_darwin')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Update gamepad mappings
        id: gamepad
        run: |
          BRLS_GLFW="library/borealis/library/lib/extern/glfw"
          cmake -P ${BRLS_GLFW}/CMake/GenerateMappings.cmake  ${BRLS_GLFW}/src/mappings.h.in  ${BRLS_GLFW}/src/mappings.h

      - name: Build
        env:
          DYLD_LIBRARY_PATH: ${{ runner.temp }}/lib
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH=${{ runner.temp }} \
            -DPLATFORM_DESKTOP=ON \
            -DMAC_${{ matrix.arch }}=ON \
            -DBRLS_UNITY_BUILD=OFF \
            -DVERSION_BUILD=${{ github.run_number }}
          make -C build -j$(sysctl -n hw.ncpu)

      - name: Bundle
        run: |
          mkdir -p dist
          mv build/wiliwili.app dist/
          cp ./scripts/mac/readme.txt dist/readme.txt
          create-dmg --window-pos 200 120 --window-size 800 400 \
            --icon-size 100 --icon "wiliwili.app" 200 190 \
            --icon "readme.txt" 400 100 --hide-extension "wiliwili.app" \
            --app-drop-link 600 185  --volicon ./scripts/mac/dmg.icns \
            --volname "wiliwili" wiliwili-macOS-${{ matrix.arch }}-${{ github.run_number }}.dmg "dist/"

      - name: Upload dist
        if: matrix.arch != 'Universal' || ( matrix.arch == 'Universal' && github.event.inputs.universal_macos == 'true')
        uses: actions/upload-artifact@v6
        with:
          name: wiliwili-macOS-${{ matrix.arch }}-${{ github.run_number }}
          path: wiliwili-*.dmg

  build-flatpak:
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    strategy:
      matrix:
        include:
          - { arch: x86_64, runner: ubuntu-24.04 }
          - { arch: aarch64, runner: ubuntu-24.04-arm }
        arch: [ x86_64, aarch64 ]
        driver: [ gl, gles2 ]
        exclude:
          - { arch: x86_64, driver: gles2 }
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 2
          fetch-tags: true

      - name: Add OpenGL ES 2.0 build option
        if: matrix.driver == 'gles2'
        run: |
          sed -i 's/USE_GLES2=OFF/USE_GLES2=ON/' .flatpak-manifest.yml

      - name: Install deps
        run: |
          BRLS_GLFW="library/borealis/library/lib/extern/glfw/"
          cmake -P ${BRLS_GLFW}/CMake/GenerateMappings.cmake  ${BRLS_GLFW}/src/mappings.h.in  ${BRLS_GLFW}/src/mappings.h

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.7
        with:
          bundle: wiliwili-Linux-${{ matrix.arch }}-${{ matrix.driver }}-${{ github.run_number }}.flatpak
          manifest-path: .flatpak-manifest.yml
          cache-key: flatpak-builder-${{ matrix.driver }}-${{ hashFiles('.flatpak-manifest.yml') }}
          verbose: true
          arch: ${{ matrix.arch }}
          upload-artifact: false

      - uses: actions/upload-artifact@v6
        with:
          name: wiliwili-Linux-${{ matrix.arch }}-${{ matrix.driver }}-${{ github.run_number }}
          path: wiliwili-Linux-*.flatpak
          if-no-files-found: error

  build-vita:
    name: build-psv
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { driver: gxm,   docker: latest-gxm, cmake: "-DUSE_GXM=ON -DUSE_VITA_SHARK=OFF" }
          - { driver: gles2, docker: latest,     cmake: "-DUSE_SYSTEM_SDL2=ON -DMPV_NO_FB=ON" }
        driver: [ gxm, gles2 ]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 2
          fetch-tags: true

      - name: Build wiliwili
        run: |
          docker run --rm -v $(pwd):/src/ xfangfang/wiliwili_psv_builder:${{ matrix.docker }} \
            "cmake -B build -G Ninja -DPLATFORM_PSV=ON -DUSE_SYSTEM_CURL=ON \
               -DBRLS_UNITY_BUILD=OFF -DCMAKE_BUILD_TYPE=Release -DSIMPLE_HIGHLIGHT=ON ${{ matrix.cmake }} && \
             cmake --build build && \
             mv build/wiliwili.self build/eboot.bin"

      - name: Upload vpk
        uses: actions/upload-artifact@v6
        with:
          name: wiliwili-PSVita-${{ matrix.driver }}-${{ github.run_number }}
          path: build/wiliwili.vpk

      - name: Upload eboot
        uses: actions/upload-artifact@v6
        with:
          name: psv_dev_eboot_${{ matrix.driver }}.bin
          path: build/eboot.bin

      - name: Upload elf
        uses: actions/upload-artifact@v6
        with:
          name: psv_dev_elf_${{ matrix.driver }}
          path: build/wiliwili
